### ISSUE TITLE
[HEAP] Teacher Tests don't test putting after getting

### ISSUE THREAD

**Issue by reckerp** [FontysVenlo/alda_sorting_api#2]
**Describe the bug**
The problem is that the teacher tests on code grade do not try to add an element to the heap after getting an element. Not testing this could lead to passing tests even though the heap(sort) is not fully functional.

**To Reproduce**
- build up a heap
- get some items
- put some items
- get some items again
- Check if the order is still correct/heap is
correctly built

**Comment by Bonajo** [comment]
Fixed in new version.
